steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/pear-dev-teamv1/dev-team-pear-agenten:$COMMIT_SHA', '-t', 'gcr.io/pear-dev-teamv1/dev-team-pear-agenten:latest', './pear-backend']
images:
  - 'gcr.io/pear-dev-teamv1/dev-team-pear-agenten:$COMMIT_SHA'
  - 'gcr.io/pear-dev-teamv1/dev-team-pear-agenten:latest'
# Logging ohne Bucket konfigurieren
options:
  logging: LEGACY