name: PEAR Demo Workflow

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Demo-Aufgabe: Dokumentationseintrag erzeugen
        run: |
          python scripts/demo_workflow_test.py
      - name: Commit & Push Demo-Doku
        run: |
          git config --global user.name "pear-bot"
          git config --global user.email "pear-bot@users.noreply.github.com"
          git add docs/dokumentation-pear.md
          git commit -m "[PEAR] Demo: Automatischer Doku-Eintrag vom $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nichts zu committen"
          git push
